#!/bin/bash

unplugged=$(tail -n 1 /etc/udev/battery_logging/disconnect.log | awk '{print $3}')
now=$(date +%s)
elapsed=$((now - unplugged))
hours=$(($elapsed / 3600))
minutes=$((($elapsed / 60) % 60))
seconds=$(($elapsed % 60))
printf "on battery: %02d:%02d:%02d\n" $hours $minutes $seconds
